### ISSUE TITLE
Tensorflow Illegal Instruction

### ISSUE THREAD

**Issue by GeovaneW96** [SciSharp/TensorFlow.NET#466]
Hi,

I use TensorFlow.NET in my application and it works fine in my PC. But, when installing at a Windows Server, I get a Faulting module exception for tensorflow.DLL.

Environment: 
Windows Server R2 2012
![pc](https://user-images.githubusercontent.com/19267390/70828946-3734df80-1dcb-11ea-9e3a-4fef7ee7ffdf.png)

Build:
Tensorflow.NET v0.12.0 (tried other versions too)
SciSharp.TensorFlow.Redist (CPU) 1.15.0 (tried other version too)
Target platform x64

Error: 

![image](https://user-images.githubusercontent.com/19267390/70829121-a0b4ee00-1dcb-11ea-89aa-c73b4031cc29.png)

When running from Visual Studio the only ouput is "Application exited with code 0xc000001d Illegal Instruction"

**Comment by GeovaneW96** [comment]
Just got an extra info..

**System.DllNotFoundException: Unable to load DLL 'tensorflow': A dynamic link library (DLL) initialization routine failed. (Exception from HRESULT: 0x8007045A)   at Tensorflow.c_api.TF_NewGraph()   at Tensorflow.Graph..ctor()**

**Comment by GeovaneW96** [comment]
Could make it work by downloading tensorflow.dll from here:

https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-1.3.0-rc2.zip

**Comment by Oceania2018** [comment]
Resolved? You could download from [here](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/) as well.

**Comment by GeovaneW96** [comment]
I had already tried downloading those versions through NuGet...

And it's actually not resolved... 
I just ended up with a new problem.

This exception is now thrown when initializing the Graph:
**Exception thrown: 'System.EntryPointNotFoundException' in TensorFlow.NET.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: module_apply_default/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D_Fold = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], explicit_paddings=[], padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true](module_apply_default/hub_input/FakeQuantWithMinMaxArgs_1, module_apply_default/MobilenetV1/MobilenetV1/Conv2d_0/weights_quant/FakeQuantWithMinMaxVars). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
Exception thrown: 'Tensorflow.TensorflowException' in TensorFlow.NET.dll**

And also this:

System.TypeInitializationException: The type initializer for 'Tensorflow.Binding' threw an exception. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'TFE_NewContextOptions' in DLL 'tensorflow'.   at Tensorflow.c_api.TFE_NewContextOptions()   at Tensorflow.tensorflow..ctor()   --- End of inner exception stack trace ---   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)   at System.Activator.CreateInstance[T]()   at Tensorflow.Binding.New[T]()   at Tensorflow.Binding..cctor()   --- End of inner exception stack trace ---   at Tensorflow.Binding.get_tf()   at LayoutRecognizer.ReadTensorFromImageFile(String file_name, Int32 input_height, Int32 input_width, Int32 input_mean, Int32 input_std)


Seems like Tensorflow.NET is not compatible with tensorflow 1.3.0?

**Comment by Oceania2018** [comment]
@GeovaneW96 You should keep the tensorflow dll version compatile with the model training version.

**Comment by GeovaneW96** [comment]
Ok. 
I trained my models with tf v 1.14
I'll try downgrading to v1.13.0rc2 and i'll come back.

**Comment by salocinx** [comment]
> Ok. I trained my models with tf v 1.14 I'll try downgrading to v1.13.0rc2 and i'll come back.

Did you solve this issue? I am currently having the same issue, also using an Intel Xeon CPU, could this be the problem?
